package tulos;
// Generated by ComTest BEGIN
import static org.junit.Assert.* ;
import org.junit.*;
import tulos.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.06.29 10:56:05 // Generated by ComTest
 *
 */
@SuppressWarnings("unused")
public class MatkatTest {



  // Generated by ComTest BEGIN
  /** testAnnaMatka30 */
  @Test
  public void testAnnaMatka30() {    // Matkat: 30
    Matkat matkat = new Matkat(); 
    Matka matka1 = new Matka(); 
    Matka matka2 = new Matka(); 
    Matka matka3 = new Matka(); 
    matka1.rekisteroi(); 
    matka2.rekisteroi(); 
    matka3.rekisteroi(); 
    matkat.lisaa(matka1); 
    matkat.lisaa(matka2); 
    matkat.lisaa(matka3); 
    int a = matka1.getId(); 
    assertEquals("From: Matkat line: 43", true, matka1 == matkat.annaMatka(a)); 
    assertEquals("From: Matkat line: 44", true, matka2 == matkat.annaMatka(a+1)); 
    assertEquals("From: Matkat line: 45", false, matka3 == matkat.annaMatka(a+5)); 
  } // Generated by ComTest END
}