package tulos;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tulos.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.06.28 11:10:01 // Generated by ComTest
 *
 */
@SuppressWarnings("unused")
public class UrheilijatTest {



  // Generated by ComTest BEGIN
  /** testLisaa18 */
  @Test
  public void testLisaa18() {    // Urheilijat: 18
    Urheilijat urheilijat = new Urheilijat(); 
    Urheilija vaiski1 = new Urheilija(); 
    Urheilija vaiski2 = new Urheilija(); 
    urheilijat.lisaa(vaiski1); assertEquals("From: Urheilijat line: 22", 1, urheilijat.getLkm()); 
    urheilijat.lisaa(vaiski2); assertEquals("From: Urheilijat line: 23", 2, urheilijat.getLkm()); 
    urheilijat.lisaa(vaiski1); assertEquals("From: Urheilijat line: 24", 3, urheilijat.getLkm()); 
    assertEquals("From: Urheilijat line: 25", vaiski1, urheilijat.anna(0)); 
    assertEquals("From: Urheilijat line: 26", vaiski2, urheilijat.anna(1)); 
    assertEquals("From: Urheilijat line: 27", vaiski1, urheilijat.anna(2)); 
    assertEquals("From: Urheilijat line: 28", false, urheilijat.anna(1) == vaiski1); 
    assertEquals("From: Urheilijat line: 29", true, urheilijat.anna(0) == vaiski1); 
    try {
    assertEquals("From: Urheilijat line: 30", vaiski1, urheilijat.anna(3)); 
    fail("Urheilijat: 30 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    urheilijat.lisaa(vaiski1); assertEquals("From: Urheilijat line: 31", 4, urheilijat.getLkm()); 
    urheilijat.lisaa(vaiski1); assertEquals("From: Urheilijat line: 32", 5, urheilijat.getLkm()); 
    urheilijat.lisaa(vaiski1); assertEquals("From: Urheilijat line: 33", 6, urheilijat.getLkm()); 
  } // Generated by ComTest END
}