package tulos;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import tulos.*;

/**
 * Test class made by ComTest
 * @version 2018.06.22 13:38:42 // Generated by ComTest
 *
 */
@SuppressWarnings("unused")
public class UrheilijaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi41 */
  @Test
  public void testRekisteroi41() {    // Urheilija: 41
    Urheilija vaiski1 = new Urheilija(); 
    assertEquals("From: Urheilija line: 43", 0, vaiski1.getId()); 
    vaiski1.rekisteroi(); 
    Urheilija vaiski2 = new Urheilija(); 
    vaiski2.rekisteroi(); 
    int n1 = vaiski1.getId(); 
    int n2 = vaiski2.getId(); 
    assertEquals("From: Urheilija line: 49", n2-1, n1); 
    vaiski1.rekisteroi(); 
    assertEquals("From: Urheilija line: 51", n1, vaiski1.getId()); 
  } // Generated by ComTest END
}