package tulos;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tulos.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.07.04 16:12:33 // Generated by ComTest
 *
 */
@SuppressWarnings("unused")
public class AikaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi64 */
  @Test
  public void testRekisteroi64() {    // Aika: 64
    Aika aika = new Aika(); 
    assertEquals("From: Aika line: 66", 0, aika.getId()); 
    aika.rekisteroi(); 
    Aika aika2 = new Aika(); 
    aika2.rekisteroi(); 
    int n1 = aika.getId(); 
    int n2 = aika2.getId(); 
    assertEquals("From: Aika line: 72", n2-1, n1); 
    aika.rekisteroi(); 
    assertEquals("From: Aika line: 74", n1, aika.getId()); 
  } // Generated by ComTest END
}