package tulos;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import tulos.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.07.04 16:09:55 // Generated by ComTest
 *
 */
@SuppressWarnings("unused")
public class AjatTest {



  // Generated by ComTest BEGIN
  /** testAnnaAjat40 */
  @Test
  public void testAnnaAjat40() {    // Ajat: 40
    Ajat ajat = new Ajat(); 
    Aika aika21 = new Aika(2); ajat.lisaa(aika21); 
    Aika aika11 = new Aika(1); ajat.lisaa(aika11); 
    Aika aika22 = new Aika(2); ajat.lisaa(aika22); 
    Aika aika12 = new Aika(1); ajat.lisaa(aika12); 
    Aika aika23 = new Aika(2); ajat.lisaa(aika23); 
    Aika aika51 = new Aika(5); ajat.lisaa(aika51); 
    List<Aika> loytyneet; 
    loytyneet = ajat.annaAjat(3); 
    assertEquals("From: Ajat line: 53", 0, loytyneet.size()); 
    loytyneet = ajat.annaAjat(1); 
    assertEquals("From: Ajat line: 55", 2, loytyneet.size()); 
    assertEquals("From: Ajat line: 56", true, loytyneet.get(0) == aika11); 
    loytyneet = ajat.annaAjat(5); 
    assertEquals("From: Ajat line: 58", 1, loytyneet.size()); 
    assertEquals("From: Ajat line: 59", true, loytyneet.get(0) == aika51); 
  } // Generated by ComTest END
}