package tulos;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import org.junit.*;

import tulos.*;

/**
 * Test class made by ComTest
 * @version 2018.06.23 13:33:16 // Generated by ComTest
 *
 */
@SuppressWarnings("unused")
public class MatkaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi23 */
  @Test
  public void testRekisteroi23() {    // Matka: 23
    Matka matka = new Matka(); 
    assertEquals("From: Matka line: 25", 0, matka.getId()); 
    matka.rekisteroi(); 
    Matka matka2 = new Matka(); 
    matka2.rekisteroi(); 
    int n1 = matka.getId(); 
    int n2 = matka2.getId(); 
    assertEquals("From: Matka line: 31", n2-1, n1); 
    matka.rekisteroi(); 
    assertEquals("From: Matka line: 33", n1, matka.getId()); 
  } // Generated by ComTest END
}