package tulos;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tulos.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.07.04 16:48:37 // Generated by ComTest
 *
 */
@SuppressWarnings("unused")
public class RekisteriTest {



  // Generated by ComTest BEGIN
  /** testLisaa21 */
  @Test
  public void testLisaa21() {    // Rekisteri: 21
    Rekisteri reki = new Rekisteri(); 
    Urheilija vaiski1 = new Urheilija(); 
    Urheilija vaiski2 = new Urheilija(); 
    assertEquals("From: Rekisteri line: 25", 0, reki.getUrheilijaLkm()); 
    reki.lisaa(vaiski1); assertEquals("From: Rekisteri line: 26", 1, reki.getUrheilijaLkm()); 
    reki.lisaa(vaiski2); assertEquals("From: Rekisteri line: 27", 2, reki.getUrheilijaLkm()); 
    reki.lisaa(vaiski1); assertEquals("From: Rekisteri line: 28", 3, reki.getUrheilijaLkm()); 
    assertEquals("From: Rekisteri line: 29", vaiski1, reki.annaUrheilija(0)); 
    assertEquals("From: Rekisteri line: 30", vaiski2, reki.annaUrheilija(1)); 
    assertEquals("From: Rekisteri line: 31", vaiski1, reki.annaUrheilija(2)); 
    assertEquals("From: Rekisteri line: 32", false, reki.annaUrheilija(1) == vaiski1); 
    assertEquals("From: Rekisteri line: 33", true, reki.annaUrheilija(0) == vaiski1); 
    try {
    assertEquals("From: Rekisteri line: 34", vaiski1, reki.annaUrheilija(3)); 
    fail("Rekisteri: 34 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    reki.lisaa(vaiski1); assertEquals("From: Rekisteri line: 35", 4, reki.getUrheilijaLkm()); 
    reki.lisaa(vaiski1); assertEquals("From: Rekisteri line: 36", 5, reki.getUrheilijaLkm()); 
    reki.lisaa(vaiski1); assertEquals("From: Rekisteri line: 37", 6, reki.getUrheilijaLkm()); 
  } // Generated by ComTest END
}